### ISSUE TITLE
add Bandwidth stat in node view page

### ISSUE THREAD

**Issue by flysatss** [storjdashboard/storjdashboard-internal#3]
add, curent day Bandwidth(speed metric) in line after Bandwidth(traffic metric)

**Comment by storjdashboard** [comment]
Hi @flysatss 

Do you mean so that you dont have the additional information under the overall Mbit/s

I've tried to draw this out - Hopefully you can understand it - Let me know if this is what you mean 

![image](https://user-images.githubusercontent.com/102604897/222957331-80faf7ca-667f-41b1-9def-30eab17b1e13.png)

**Comment by flysatss** [comment]
![image](https://user-images.githubusercontent.com/6475075/222967444-698c1ecc-0b04-40dc-93ee-92d82b85c64b.png)

**Comment by ItsHass** [comment]
Hi @flysatss 

Can certainly look to implement this in a future update!

Appriciate your feedback on our community project.

**Comment by storjdashboard** [comment]
updated in 1.0.1.1
