### ISSUE TITLE
Hang index page if failure node

### ISSUE THREAD

**Issue by flysatss** [storjdashboard/storjdashboard-internal#4]
Hang index page if failure node.
dead node, or disconnect node leads to a hang, or a very strong slowdown in the rendering of the main page

**Comment by storjdashboard** [comment]
Hi @flysatss 

We're Looking to implement JQuery, but this may take some time - We will provide updates as we go through this. 

However, during some testing on our Web Portal ([my.storjdashboard.com](https://my.storjdashboard.com)) it has only slightly improved the speed as it will requires timeout which is why the page can take some time to load.

We maybe able to also in 'settings' but a variable function for the timeout so you could indivudally choose what timeout limit you would want the page to have. 

We will update this when we have a roadmap for this one.

Many thanks

**Comment by storjdashboard** [comment]
better error management now in place since 1.0.1.1
